Spring:
  data:
    # redis 配置
    redis:
      # 地址
      host: localhost
      # 端口，默认为6379
      port: 6379
      # 数据库索引
      database: 1
      # 密码
      password: root
      # 连接超时时间
      timeout: 10s